# SAMPLE ENV
# ROOT_PATH=/mnt/plex

version: '3'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=$PLEX_CLAIM
      - ROOT_PATH=$ROOT_PATH
    volumes:
      - ${ROOT_PATH}/config:/config
      - ${ROOT_PATH}/data/media:/media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:7878/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config
      - ${ROOT_PATH}/data:/data

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radar
    restart: always
    ports:
      - "7878:7878/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config
      - ${ROOT_PATH}/data:/data

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: always
    ports:
      - "8080:8080/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config
      - ${ROOT_PATH}/data:/data

