# SAMPLE ENV
# ROOT_PATH=/mnt/plex

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${ROOT_PATH}/config:/config/jellyfin
      - ${ROOT_PATH}/data/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - ${ROOT_PATH}/config:/app/config/jellyseerr
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    pull_policy: always
    restart: always
    ports:
      - "8989:8989/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config/sonarr
      - ${ROOT_PATH}/data:/data

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radar
    pull_policy: always
    restart: always
    ports:
      - "7878:7878/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config/radarr
      - ${ROOT_PATH}/data:/data

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    pull_policy: always
    restart: always
    ports:
      - "8080:8080/tcp"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${ROOT_PATH}/config:/config/sabnzbd
      - ${ROOT_PATH}/data:/data
